### PR TITLE
boost sound without radio

### PR DESCRIPTION
**Pull request by andryblack**

### CODE REVIEW

**Comment by fulldecent** [comment]
Is the idea here to run the same code on each thread? Should the threads equal the number of processors on the system?

**Comment by andryblack** [comment]
Main idea just modulate power consumption, more power consumption in "hi" half-wave - more sound power. Most likely sound from inductors on the supply circuit.

**Comment by EzoeRyou** [comment]
I confirmed this noticeably increase the output.

**Comment by fulldecent** [comment]
Thank you, this is merged in the `Using counter and threads` flavor. I am using "threads" to describe this feature.

**Pull request closed without merging**
