### PR TITLE
JS port

### PR DESCRIPTION
**Pull request by quanyang**
Was curious, so I ported the code to vanillaJS.

Works nicely on my MBP Retina Late 2013, on the Google Chrome browser, simply by launching the html page and clicking the button. (1560Khz)

No dependencies required.

There's a bit of noise though.

### CODE REVIEW

**Comment by fulldecent** [comment]
This is awesome! 

Can you please share a video or or your results / distance / what receiver?

**Comment by quanyang** [comment]
AR1741 Multiband Receiver, not mine though.

Has to be really near currently for it to be audible, could probably work at removing the noise or to strengthen the signal.

https://drive.google.com/file/d/0B5-B1W67iMNnRnh0Rlo0UTQyazA/view?usp=sharing

**Comment by fulldecent** [comment]
谢谢! This looks great. I made a small change and it is less noisy now. Please let me know if this is producing good results for you too.

**Comment by quanyang** [comment]
yep, this is producing better results for me. Interestingly it was working across multiple frequencies when my MBP was charging.

https://drive.google.com/file/d/0B5-B1W67iMNnR1BUZmZjSHU0R28/view?usp=sharing

**Comment by fulldecent** [comment]
Thank you, I added the test data to
https://github.com/fulldecent/system-bus-radio/blob/master/TEST-DATA.tsv

**Comment by quanyang** [comment]
Awesome! Glad to be of help. :+1:

**Pull request merged**
