### PR TITLE
Add linux support

### PR DESCRIPTION
**Pull request by hmage**
Fixes issue #2. 

I don't have an AM receiver so I can't check if it actually works. But platform-specific parts of the code are now guarded with #ifdefs.

### CODE REVIEW

**Comment by fulldecent** [comment]
This looks good, thank you! Can anyone using Linux confirm it works?

Also, I notice the sleep timer uses a relative time. It would be preferable if it is possible to use an absolute time. The `clock_sleep_trap()` and more importantly `clock_sleep_internal()` show how Mac does it.

On Linux, the call `clock_nanosleep()` may also allow specifying absolute time. It is documented at http://man7.org/linux/man-pages/man2/clock_nanosleep.2.html

**Comment by hmage** [comment]
absolute time is not monotonic. As in, ntp might adjust the time backwards one year and your absolute time will happen only after one year.

Will re-do, but that's horrible decision to use absolute wallclock time for a program that doesn't need one.

**Comment by fulldecent** [comment]
Good point. My intention is to avoid any clock drift that results from calling nanosleep itself.

For example:

    for (int i=0; i<100000; i++) {
        nanosleep(50);
    }

would sleep more than 50 * 100000 because of the `i++` and the `i<100000`.

This might matter when the signal frequency in increased.

Do you have any advice for this?

**Comment by hmage** [comment]
Also good point. I have no off the top solution for this, but there must be a way for this. I guess reading how timing in software oscillators works should be a good starting point.

**Comment by somini** [comment]
I can confirm this works on Linux.
I only have access to the lousiest AM receiver, so it only works a few cm from the radio, and there's a lot of noise.
I'll try and upload a video soon.

**Comment by somini** [comment]
https://www.youtube.com/watch?v=Nroc2BtO6NU
I merged the other PR, and it also plays the SMB Theme.

**Comment by fulldecent** [comment]
@somini thank you, just added your result to https://github.com/fulldecent/system-bus-radio/blob/master/HARDWARE-INFO.md

**Comment by SyntaxColoring** [comment]
I can also confirm that this works on Linux.  I used a Lenovo ThinkPad T440s and a clock radio tuned to 1630 kHz.  I got quite clear sound at up to 12 inches.

**Comment by hmage** [comment]
Re-based. No changes yet to address issues raised here.

**Comment by hmage** [comment]
Changed to use relative time only.

**Comment by gabtremblay** [comment]
Interestingly, it builds, but it does not seem to work in a VM. The code launches but there's no delay at all.

**Comment by rocketinventor** [comment]
@gabtremblay I would be pretty surprised if it worked in a VM

**Comment by gabtremblay** [comment]
You may want to check the c++11 port, which works properly. Maybe it's a time source related problem.

Will test the emmition behavior tomorrow with my fcube

**Comment by fulldecent** [comment]
Thank you, merged!

**Pull request merged**
