### PR TITLE
Updated Test-Data.tsv

### PR DESCRIPTION
**Pull request by troygiorshev**
Added my test, and fixed the resulting quotation mark mess.  (This also fixed a few previous quotation mark problems)

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you!

May we have one more reviewer here?

**Comment by TomasHubelbauer** [comment]
Hey, this broke the GitHub viewer again.

**Comment by troygiorshev** [comment]
Whoops, I'll look at that.

**Comment by troygiorshev** [comment]
There we go.  Works now.  Excel automatically adds quotation marks around everything, and my "brilliant solution" for removing them broke everything.

**Comment by TomasHubelbauer** [comment]
@troygiorshev Looks great now! And Excel sucks. :-D

**Comment by fulldecent** [comment]
Thanks for cleaning this up!

**Pull request merged**
